INSERT INTO saas.translations (key, language, value) VALUES
-- Navigation
('nav.dashboard', 'en', 'Dashboard'),
('nav.dashboard', 'pt', 'Painel'),
('nav.profile', 'en', 'Profile'),
('nav.profile', 'pt', 'Perfil'),
('nav.settings', 'en', 'Settings'),
('nav.settings', 'pt', 'Configurações'),
('nav.logout', 'en', 'Logout'),
('nav.logout', 'pt', 'Sair'),

-- Profile page
('profile.title', 'en', 'Profile Settings'),
('profile.title', 'pt', 'Configurações do Perfil'),
('profile.subtitle', 'en', 'Manage your account information'),
('profile.subtitle', 'pt', 'Gerencie suas informações da conta'),
('profile.personal_info', 'en', 'Personal Information'),
('profile.personal_info', 'pt', 'Informações Pessoais'),
('profile.personal_info_desc', 'en', 'Update your personal details'),
('profile.personal_info_desc', 'pt', 'Atualize seus dados pessoais'),
('profile.avatar', 'en', 'Avatar'),
('profile.avatar', 'pt', 'Avatar'),
('profile.upload_avatar', 'en', 'Upload Avatar'),
('profile.upload_avatar', 'pt', 'Enviar Avatar'),
('profile.full_name', 'en', 'Full Name'),
('profile.full_name', 'pt', 'Nome Completo'),
('profile.email', 'en', 'Email'),
('profile.email', 'pt', 'E-mail'),
('profile.save_changes', 'en', 'Save Changes'),
('profile.save_changes', 'pt', 'Salvar Alterações'),
('profile.saving', 'en', 'Saving...'),
('profile.saving', 'pt', 'Salvando...'),

-- Settings page
('settings.title', 'en', 'Settings'),
('settings.title', 'pt', 'Configurações'),
('settings.subtitle', 'en', 'Manage your application preferences'),
('settings.subtitle', 'pt', 'Gerencie suas preferências do aplicativo'),
('settings.notifications', 'en', 'Notifications'),
('settings.notifications', 'pt', 'Notificações'),
('settings.notifications_desc', 'en', 'Configure how you receive notifications'),
('settings.notifications_desc', 'pt', 'Configure como você recebe notificações'),
('settings.email_notifications', 'en', 'Email Notifications'),
('settings.email_notifications', 'pt', 'Notificações por E-mail'),
('settings.email_notifications_desc', 'en', 'Receive email notifications'),
('settings.email_notifications_desc', 'pt', 'Receber notificações por e-mail'),
('settings.marketing_emails', 'en', 'Marketing Emails'),
('settings.marketing_emails', 'pt', 'E-mails de Marketing'),
('settings.marketing_emails_desc', 'en', 'Receive marketing emails'),
('settings.marketing_emails_desc', 'pt', 'Receber e-mails de marketing'),
('settings.appearance', 'en', 'Appearance'),
('settings.appearance', 'pt', 'Aparência'),
('settings.appearance_desc', 'en', 'Customize the look and feel'),
('settings.appearance_desc', 'pt', 'Personalize a aparência'),
('settings.theme', 'en', 'Theme'),
('settings.theme', 'pt', 'Tema'),
('settings.theme_light', 'en', 'Light'),
('settings.theme_light', 'pt', 'Claro'),
('settings.theme_dark', 'en', 'Dark'),
('settings.theme_dark', 'pt', 'Escuro'),
('settings.theme_system', 'en', 'System'),
('settings.theme_system', 'pt', 'Sistema'),
('settings.language', 'en', 'Language'),
('settings.language', 'pt', 'Idioma'),
('settings.language_en', 'en', 'English'),
('settings.language_en', 'pt', 'Inglês'),
('settings.language_pt', 'en', 'Portuguese'),
('settings.language_pt', 'pt', 'Português'),
('settings.save_all', 'en', 'Save All Settings'),
('settings.save_all', 'pt', 'Salvar Todas as Configurações'),

-- Common
('common.loading', 'en', 'Loading...'),
('common.loading', 'pt', 'Carregando...'),
('common.success', 'en', 'Success'),
('common.success', 'pt', 'Sucesso'),
('common.error', 'en', 'Error'),
('common.error', 'pt', 'Erro'),
('common.saved', 'en', 'Settings saved successfully'),
('common.saved', 'pt', 'Configurações salvas com sucesso'),
('common.save_error', 'en', 'Failed to save settings'),
('common.save_error', 'pt', 'Falha ao salvar configurações'),
('common.profile_updated', 'en', 'Profile updated successfully'),
('common.profile_updated', 'pt', 'Perfil atualizado com sucesso'),
('common.profile_error', 'en', 'Failed to update profile'),
('common.profile_error', 'pt', 'Falha ao atualizar perfil'),
('common.load_error', 'en', 'Failed to load'),
('common.load_error', 'pt', 'Falha ao carregar');